[package]
name = "budget-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
yew-router = { git = "https://github.com/yewstack/yew/" }
budget-models = { path = "../models" }
anyhow = "1.0"
wasm-logger = "0.2"
log = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["Request", "Window"] }
wasm-bindgen = { version = "0.2" }
wasm-bindgen-futures = { version = "0.4" }
serde = { version = "1.0" }
http = "0.2"
