[package]
name = "budget-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
yew-router = { git = "https://github.com/yewstack/yew/" }
budget-models = { path = "../models" }
anyhow = "1.0"
wasm-logger = "0.2"
log = "0.4"
