DROP TRIGGER update_initial_balance_modtime ON initial_balances;
DROP FUNCTION update_modified_column;
DROP TABLE initial_balances;
DROP TABLE transactions;
DROP TABLE budget_items;
DROP TYPE TransactionType;
DROP TABLE categories;
DROP TABLE one_time_budgets;
DROP TABLE periodic_budgets;
DROP TABLE accounts;
DROP TYPE AccountType;
