//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize,
)]
#[sea_orm(table_name = "line_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub summary: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::planned_transactions::Entity")]
    PlannedTransactions,
    #[sea_orm(has_many = "super::real_transactions::Entity")]
    RealTransactions,
}

impl Related<super::planned_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlannedTransactions.def()
    }
}

impl Related<super::real_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RealTransactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
