//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize,
)]
#[sea_orm(table_name = "line_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub summary: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::line_item_instances::Entity")]
    LineItemInstances,
}

impl Related<super::line_item_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LineItemInstances.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
