//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize,
)]
#[sea_orm(table_name = "line_item_instances")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub summary: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub from_account: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub to_account: Option<String>,
    pub amount: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::FromAccount",
        to = "super::accounts::Column::Name",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Accounts2,
    #[sea_orm(
        belongs_to = "super::line_items::Entity",
        from = "Column::Summary",
        to = "super::line_items::Column::Summary",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    LineItems,
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::ToAccount",
        to = "super::accounts::Column::Name",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Accounts1,
}

impl Related<super::line_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LineItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
