//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize,
)]
#[sea_orm(table_name = "transactions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub summary: String,
    pub date: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub account: String,
    pub amount: i64,
    pub completed_by: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::Account",
        to = "super::accounts::Column::Name",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Accounts,
    #[sea_orm(has_many = "super::planned_transactions::Entity")]
    PlannedTransactions,
    #[sea_orm(has_many = "super::real_transactions::Entity")]
    RealTransactions,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::CompletedBy",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SelfRef,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::planned_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlannedTransactions.def()
    }
}

impl Related<super::real_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RealTransactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
