//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "accounttype")]
pub enum Accounttype {
    #[sea_orm(string_value = "checking")]
    Checking,
    #[sea_orm(string_value = "credit")]
    Credit,
    #[sea_orm(string_value = "loan")]
    Loan,
    #[sea_orm(string_value = "saving")]
    Saving,
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "transactiontype")]
pub enum Transactiontype {
    #[sea_orm(string_value = "expense")]
    Expense,
    #[sea_orm(string_value = "income")]
    Income,
    #[sea_orm(string_value = "payment")]
    Payment,
    #[sea_orm(string_value = "transfer")]
    Transfer,
}
