[package]
name = "chart-js"
version = "3.9.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.145", features = ["derive"] }
serde-wasm-bindgen = "0.4.5"
wasm-bindgen = "0.2.83"
web-sys = { version = "0.3.60", features = ["HtmlCanvasElement"] }
