[package]
name = "budget-models"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { git = "https://github.com/chronotope/chrono", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
strum = "0.24"
strum_macros = "0.24"
